#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export ANDROID_HOME=~/tools/androidsdk
export GOPATH=~/tools/go

export DS5PROXY_HOST=http://chicken.datasplice.com
export DS5PROXY_PORT=80
