#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

ulimit -n 1024
alias ds='echo $DS5PROXY_HOST:$DS5PROXY_PORT'
alias git-delete-merged='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
alias chrome='open /Applications/Google\ Chrome.app'
alias canary='open /Applications/Google\ Chrome\ Canary.app'


path=(
  $path
  $ANDROID_HOME/tools
  $ANDROID_HOME/platform-tools
  $GOPATH/bin
  $HOME/.npm-packages/bin
)

eval "$(gulp --completion=zsh)"
